/**
 * The starter foods and aisles every garnish database begins with — the
 * vocabulary an import is read against before the household has added a
 * food of its own (decisions.md row 121). Drawn from the ingredient lines of
 * some two thousand recipes on Australian and British sites, ranked by how
 * often each food is written, with a US cookbook corpus as a second opinion.
 *
 * - **Names** are what an Australian recipe and supermarket call the food, in
 *   lower case: caster sugar, plain flour, capsicum, coriander, spring onion,
 *   prawn, thickened cream.
 * - **Aliases** are the other names the same purchase goes by: the US and UK
 *   words (cilantro, scallion, all-purpose flour, aubergine), other spellings
 *   (chilli and chili, yoghurt and yogurt, fetta and feta), and the few
 *   qualifiers recipes put before a food so often they are its name
 *   (extra virgin, freshly ground). An alias is matched exactly, so a
 *   countable one lists its plural too.
 * - **Compounds** are here whenever their head is: the matcher keeps the
 *   longest name a line starts with, so "lemon" alone would read "lemon
 *   juice" as a lemon and drop the juice. Lemon juice, garlic powder, egg
 *   yolk, celery salt, butter beans and milk chocolate are foods of their own
 *   so the head never swallows them.
 * - **Granularity** follows the shelf: two things are one food when a
 *   shopper would buy either (spring onion and green onion), two foods when
 *   they would not (caster and brown sugar, thickened and pouring cream).
 *   No brands, no prepared dishes.
 *
 * The seed adds these once per database and never again (`seed.ts`), so a
 * food the household renames, merges or deletes stays as they left it. A
 * later addition to the list is a new batch with its own name, not an edit
 * to this one.
 */

/** Aisles, in the order a supermarket walks them. A new database gets them in this order. */
export const STARTER_AISLES = [
  "Fruit & veg",
  "Bakery",
  "Deli",
  "Butcher",
  "Seafood",
  "Dairy & eggs",
  "Pantry",
  "Baking",
  "Spices",
  "International",
  "Drinks",
  "Freezer",
] as const;

export type StarterAisle = (typeof STARTER_AISLES)[number];

export type StarterFood = {
  name: string;
  /** Only for a countable food: "2 lemons", never "2 flours". */
  plural?: string;
  aliases?: readonly string[];
  aisle: StarterAisle;
  /** Never added to a shopping list: what comes out of the tap or is already on the bench. */
  skipShopping?: true;
};

const produce = (name: string, plural?: string, aliases?: readonly string[]): StarterFood => ({ name, plural, aliases, aisle: "Fruit & veg" });
const aisle =
  (where: StarterAisle) =>
  (name: string, plural?: string, aliases?: readonly string[]): StarterFood => ({ name, plural, aliases, aisle: where });
const bakery = aisle("Bakery");
const deli = aisle("Deli");
const butcher = aisle("Butcher");
const seafood = aisle("Seafood");
const dairy = aisle("Dairy & eggs");
const pantry = aisle("Pantry");
const baking = aisle("Baking");
const spice = aisle("Spices");
const international = aisle("International");
const drinks = aisle("Drinks");
const freezer = aisle("Freezer");

export const STARTER_FOODS: readonly StarterFood[] = [
  // ── Fruit & veg: the onion family
  produce("onion", "onions", ["brown onion", "brown onions", "yellow onion", "yellow onions", "brown or white onion"]),
  produce("red onion", "red onions", ["purple onion", "purple onions", "spanish onion", "spanish onions", "red salad onion"]),
  produce("white onion", "white onions"),
  produce("spring onion", "spring onions", ["green onion", "green onions", "scallion", "scallions", "green onion stems", "spring onion stems"]),
  produce("shallot", "shallots", [
    "eschalot",
    "eschalots",
    "eschallot",
    "eschallots",
    "french shallot",
    "french shallots",
    "banana shallot",
    "banana shallots",
  ]),
  produce("red asian shallot", "red asian shallots", ["asian shallot", "asian shallots", "red shallot", "red shallots", "thai shallot", "thai shallots"]),
  produce("leek", "leeks"),
  produce("garlic", undefined, [
    "garlic paste",
    "head of garlic",
    "bulb of garlic",
    "grated garlic",
    "garlic clove",
    "garlic cloves",
    "garlic bulb",
    "minced garlic",
    "crushed garlic",
  ]),
  produce("garlic chives", undefined, ["chinese chives"]),
  produce("ginger", undefined, [
    "minced ginger",
    "finely grated ginger",
    "finely grated fresh ginger",
    "peeled ginger",
    "fresh ginger",
    "ginger root",
    "root ginger",
    "fresh root ginger",
    "grated ginger",
  ]),
  produce("galangal"),
  produce("lemongrass", undefined, ["lemon grass", "lemongrass stalk", "lemongrass stalks", "lemongrass stem", "lemongrass stems"]),
  produce("turmeric root", undefined, ["fresh turmeric"]),

  // ── Fruit & veg: chillies and capsicums
  produce("long red chilli", "long red chillies", [
    "red chilli",
    "red chillies",
    "fresh red chilli",
    "fresh red chillies",
    "chilli",
    "chillies",
    "chili",
    "chilies",
    "red chili",
    "red chilies",
    "fresh long red chilli",
    "fresh chilli",
    "long red chili",
  ]),
  produce("long green chilli", "long green chillies", [
    "green chilli",
    "green chillies",
    "green chili",
    "green chilies",
    "fresh green chilli",
    "green chile",
    "green chiles",
  ]),
  produce("bird's eye chilli", "bird's eye chillies", [
    "birds eye chilli",
    "bird's-eye chilli",
    "bird's-eye chillies",
    "thai chilli",
    "thai chillies",
    "red thai chilli",
    "red thai chillies",
    "small red chilli",
    "small red chillies",
  ]),
  produce("habanero chilli", "habanero chillies", [
    "habanero",
    "habaneros",
    "scotch bonnet",
    "scotch bonnet chilli",
    "scotch bonnet chillies",
    "scotch bonnet pepper",
    "scotch bonnet peppers",
  ]),
  produce("jalapeño", "jalapeños", ["jalapeno", "jalapenos", "jalapeño pepper", "jalapeño peppers", "jalapeno pepper", "jalapeno peppers"]),
  produce("capsicum", "capsicums", ["mixed-colour peppers", "mixed-colour pepper", "mixed peppers", "bell pepper", "bell peppers"]),
  produce("red capsicum", "red capsicums", ["red bell pepper", "red bell peppers", "red pepper", "red peppers"]),
  produce("green capsicum", "green capsicums", ["green bell pepper", "green bell peppers", "green pepper", "green peppers"]),
  produce("yellow capsicum", "yellow capsicums", ["yellow bell pepper", "yellow bell peppers", "yellow pepper", "yellow peppers"]),

  // ── Fruit & veg: roots and tubers
  produce("potato", "potatoes", [
    "waxy potato",
    "waxy potatoes",
    "mashed potato",
    "mashed potatoes",
    "white potato",
    "white potatoes",
    "floury potato",
    "floury potatoes",
    "starchy potato",
    "starchy potatoes",
    "all-rounder potato",
    "all-rounder potatoes",
    "brushed potato",
    "brushed potatoes",
    "sebago potato",
    "sebago potatoes",
    "desiree potato",
    "desiree potatoes",
    "russet potato",
    "russet potatoes",
    "yukon gold potato",
    "yukon gold potatoes",
    "maris piper potato",
    "maris piper potatoes",
    "washed potato",
    "washed potatoes",
    "baking potato",
    "baking potatoes",
  ]),
  produce("baby potato", "baby potatoes", [
    "baby new potatoes",
    "chat potato",
    "chat potatoes",
    "baby chat potato",
    "baby chat potatoes",
    "new potato",
    "new potatoes",
    "small potato",
    "small potatoes",
  ]),
  produce("kipfler potato", "kipfler potatoes", ["fingerling potato", "fingerling potatoes"]),
  produce("sweet potato", "sweet potatoes", ["kumara", "kumaras", "orange sweet potato", "orange sweet potatoes"]),
  produce("carrot", "carrots", ["heritage carrots", "purple carrot", "purple carrots", "dutch carrots", "baby carrot", "baby carrots"]),
  produce("parsnip", "parsnips"),
  produce("beetroot", "beetroots", ["beet", "beets", "baby beetroot", "baby beetroots"]),
  produce("radish", "radishes", ["red radish", "red radishes"]),
  produce("daikon", undefined, ["white radish", "daikon radish"]),
  produce("celeriac"),
  produce("swede", "swedes", ["rutabaga"]),
  produce("turnip", "turnips"),

  // ── Fruit & veg: squash, fruiting veg and salad
  produce("pumpkin", undefined, ["pumpkin flesh"]),
  produce("butternut pumpkin", undefined, ["butternut squash", "butternut"]),
  produce("kent pumpkin", undefined, ["jap pumpkin", "kabocha", "kabocha squash"]),
  produce("zucchini", "zucchini", ["zucchinis", "courgette", "courgettes"]),
  produce("squash", undefined, ["yellow squash", "summer squash", "pattypan squash", "button squash", "acorn squash"]),
  produce("eggplant", "eggplants", ["aubergine", "aubergines", "baby eggplant", "baby eggplants"]),
  produce("tomato", "tomatoes", [
    "mixed-colour tomatoes",
    "ripe mixed-colour tomatoes",
    "ripe tomato",
    "ripe tomatoes",
    "vine-ripened tomato",
    "vine-ripened tomatoes",
    "truss tomato",
    "truss tomatoes",
    "heirloom tomato",
    "heirloom tomatoes",
  ]),
  produce("roma tomato", "roma tomatoes", ["plum tomato", "plum tomatoes", "egg tomato", "egg tomatoes"]),
  produce("cherry tomato", "cherry tomatoes", [
    "ripe cherry tomatoes",
    "ripe mixed-colour cherry tomatoes",
    "grape tomato",
    "grape tomatoes",
    "heirloom cherry tomatoes",
    "mixed cherry tomatoes",
    "mixed-colour cherry tomatoes",
  ]),
  produce("cucumber", "cucumbers", ["telegraph cucumber", "telegraph cucumbers", "continental cucumber", "english cucumber", "english cucumbers"]),
  produce("lebanese cucumber", "lebanese cucumbers", ["persian cucumber", "persian cucumbers"]),
  produce("avocado", "avocados"),
  produce("corn cob", "corn cobs", [
    "corn on the cob",
    "cob of corn",
    "cobs of corn",
    "sweetcorn cob",
    "sweetcorn cobs",
    "ear of corn",
    "ears of corn",
    "fresh corn",
  ]),
  produce("iceberg lettuce", undefined, ["iceberg"]),
  produce("cos lettuce", undefined, [
    "little gem lettuces",
    "baby gem lettuce",
    "baby gem lettuces",
    "romaine lettuce",
    "romaine",
    "baby cos lettuce",
    "baby cos",
    "little gem lettuce",
  ]),
  produce("butter lettuce", undefined, ["butter lettuce leaves", "butterhead lettuce"]),
  produce("lettuce", undefined, ["lettuce leaves"]),
  produce("mixed salad leaves", undefined, ["mixed leaves", "salad leaves", "mesclun", "mixed greens", "salad greens", "green salad"]),
  produce("baby spinach", undefined, ["baby spinach leaves"]),
  produce("english spinach", undefined, ["spinach", "spinach leaves"]),
  produce("silverbeet", undefined, ["swiss chard", "chard", "rainbow chard"]),
  produce("kale", undefined, ["curly kale"]),
  produce("cavolo nero", undefined, ["tuscan kale", "lacinato kale", "black kale"]),
  produce("rocket", undefined, ["arugula", "baby rocket", "baby rocket leaves", "rocket leaves", "wild rocket"]),
  produce("watercress", undefined, ["cress"]),
  produce("cabbage", undefined, ["green cabbage", "white cabbage", "savoy cabbage"]),
  produce("red cabbage", undefined, ["purple cabbage"]),
  produce("wombok", undefined, ["chinese cabbage", "napa cabbage", "chinese leaf"]),
  produce("radicchio"),
  produce("witlof", undefined, ["witlof leaves", "chicory", "belgian endive", "endive", "curly endive", "frisée", "frisee"]),
  produce("bok choy", undefined, ["baby bok choy", "pak choy", "pak choi", "bok choi", "baby pak choy"]),
  produce("choy sum"),
  produce("gai lan", undefined, ["chinese broccoli", "kai lan"]),
  produce("broccoli", undefined, ["broccoli florets", "broccoli head", "head of broccoli"]),
  produce("broccolini", undefined, ["sprouting broccoli", "long-stemmed broccoli", "purple sprouting broccoli", "tenderstem broccoli", "baby broccoli"]),
  produce("cauliflower", undefined, ["cauliflower florets"]),
  produce("brussels sprout", "brussels sprouts", ["brussel sprout", "brussel sprouts"]),
  produce("celery", undefined, ["celery stalk", "celery stalks", "celery stick", "celery sticks", "celery rib", "celery ribs", "celery heart"]),
  produce("fennel", undefined, ["fennel bulb", "fennel bulbs", "baby fennel"]),
  produce("asparagus", undefined, ["asparagus spears", "asparagus spear"]),
  produce("green bean", "green beans", ["wax beans", "yellow wax beans", "french bean", "french beans", "string bean", "string beans", "runner beans"]),
  produce("snow pea", "snow peas", ["mangetout", "mange tout"]),
  produce("sugar snap pea", "sugar snap peas", ["snap peas", "sugar snaps"]),
  produce("bean sprouts", undefined, ["beansprouts", "mung bean sprouts", "bean shoots"]),
  produce("okra"),
  produce("baby corn", undefined, ["baby corn spears", "baby corncobs"]),
  produce("snake beans", undefined, ["snake bean", "long beans", "yard-long beans"]),
  produce("jerusalem artichoke", "jerusalem artichokes", ["sunchoke", "sunchokes"]),
  produce("banana leaves", undefined, ["banana leaf"]),
  produce("artichoke", "artichokes", ["globe artichoke", "globe artichokes"]),

  // ── Fruit & veg: mushrooms
  produce("button mushroom", "button mushrooms", ["mushroom", "mushrooms", "white mushroom", "white mushrooms", "cup mushroom", "cup mushrooms"]),
  produce("swiss brown mushroom", "swiss brown mushrooms", [
    "cremini mushroom",
    "cremini mushrooms",
    "chestnut mushroom",
    "chestnut mushrooms",
    "brown mushroom",
    "brown mushrooms",
  ]),
  produce("portobello mushroom", "portobello mushrooms", [
    "field mushroom",
    "field mushrooms",
    "flat mushroom",
    "flat mushrooms",
    "large flat mushrooms",
    "portabella mushroom",
    "portabella mushrooms",
  ]),
  produce("shiitake mushroom", "shiitake mushrooms", ["shiitake", "fresh shiitake mushrooms"]),
  produce("oyster mushroom", "oyster mushrooms"),
  produce("enoki mushroom", "enoki mushrooms", ["enoki"]),
  produce("wood ear mushrooms", undefined, ["wood ear mushroom", "black fungus", "wood ear fungus"]),
  produce("mixed mushrooms", undefined, ["wild mushrooms"]),

  // ── Fruit & veg: herbs
  produce("flat-leaf parsley", undefined, [
    "parsley",
    "flat leaf parsley",
    "fresh parsley",
    "fresh flat-leaf parsley",
    "italian parsley",
    "parsley leaves",
    "flat-leaf parsley leaves",
    "parsley sprigs",
    "chopped parsley",
  ]),
  produce("curly parsley"),
  produce("coriander", undefined, [
    "cilantro",
    "fresh coriander",
    "coriander leaves",
    "coriander sprigs",
    "fresh coriander leaves",
    "coriander leaves and stems",
    "chopped coriander",
    "cilantro leaves",
  ]),
  produce("basil", undefined, ["fresh basil", "basil leaves", "sweet basil", "fresh basil leaves"]),
  produce("thai basil", undefined, ["thai basil leaves", "holy basil"]),
  produce("mint", undefined, ["fresh mint", "mint leaves", "fresh mint leaves", "mint sprigs"]),
  produce("vietnamese mint", undefined, ["laksa leaves", "rau ram"]),
  produce("dill", undefined, ["fresh dill", "dill sprigs", "dill fronds"]),
  produce("chives", undefined, ["chive", "fresh chives", "snipped chives", "chopped chives"]),
  produce("rosemary", undefined, ["fresh rosemary", "rosemary sprigs", "rosemary sprig", "rosemary leaves"]),
  produce("thyme", undefined, ["fresh thyme", "thyme sprigs", "thyme sprig", "thyme leaves", "fresh thyme leaves", "lemon thyme"]),
  produce("oregano", undefined, ["fresh oregano", "oregano leaves", "fresh oregano leaves", "oregano sprigs"]),
  produce("sage", undefined, ["fresh sage", "sage leaves", "fresh sage leaves"]),
  produce("tarragon", undefined, ["fresh tarragon", "tarragon leaves"]),
  produce("marjoram", undefined, ["fresh marjoram"]),
  produce("curry leaves", undefined, ["curry leaf", "fresh curry leaves"]),
  produce("makrut lime leaves", undefined, ["makrut lime leaf", "kaffir lime leaves", "kaffir lime leaf", "lime leaves", "lime leaf"]),
  produce("microherbs", undefined, ["micro herbs"]),
  produce("chervil", undefined, ["chervil leaves"]),
  produce("pandan leaves", undefined, ["pandan leaf", "pandan"]),
  produce("taro"),

  // ── Fruit & veg: citrus, and the parts of it recipes name
  produce("lemon", "lemons", ["lemon wedges", "lemon wedge", "lemon cheeks", "lemon slices", "lemon halves"]),
  produce("lemon juice", undefined, [
    "juice of lemon",
    "juice of a lemon",
    "fresh lemon juice",
    "freshly squeezed lemon juice",
    "squeeze of lemon juice",
    "squeeze of lemon",
  ]),
  produce("lemon zest", undefined, [
    "lemon rind",
    "zest of lemon",
    "zest of a lemon",
    "grated lemon rind",
    "finely grated lemon rind",
    "finely grated lemon zest",
    "lemon peel",
  ]),
  produce("lime", "limes", ["lime wedges", "lime wedge", "lime cheeks", "lime halves"]),
  produce("lime juice", undefined, ["juice of lime", "juice of a lime", "fresh lime juice", "freshly squeezed lime juice"]),
  produce("lime zest", undefined, ["lime rind", "zest of lime", "zest of a lime", "grated lime rind"]),
  produce("orange", "oranges", ["navel orange", "navel oranges", "blood orange", "blood oranges"]),
  produce("orange zest", undefined, ["orange rind", "zest of orange", "zest of an orange", "orange peel", "grated orange rind"]),
  produce("mandarin", "mandarins", ["clementine", "clementines", "tangerine", "tangerines"]),
  produce("grapefruit", "grapefruits", ["pink grapefruit"]),

  // ── Fruit & veg: fruit
  produce("apple", "apples", [
    "red apple",
    "red apples",
    "eating apple",
    "eating apples",
    "pink lady apple",
    "pink lady apples",
    "royal gala apple",
    "royal gala apples",
    "fuji apple",
    "fuji apples",
  ]),
  produce("granny smith apple", "granny smith apples", [
    "green apple",
    "green apples",
    "granny smith",
    "cooking apple",
    "cooking apples",
    "tart apple",
    "tart apples",
  ]),
  produce("pear", "pears", ["beurre bosc pear", "beurre bosc pears", "packham pear", "packham pears"]),
  produce("banana", "bananas", ["ripe banana", "ripe bananas", "overripe bananas"]),
  produce("mango", "mangoes", ["mangos"]),
  produce("pineapple", "pineapples", ["fresh pineapple"]),
  produce("strawberry", "strawberries", ["fresh strawberries"]),
  produce("raspberry", "raspberries", ["fresh raspberries"]),
  produce("blueberry", "blueberries", ["fresh blueberries"]),
  produce("blackberry", "blackberries"),
  produce("cranberry", "cranberries", ["fresh cranberries", "frozen cranberries"]),
  produce("cherry", "cherries", ["fresh cherries"]),
  produce("grapes", undefined, ["grape", "red grapes", "green grapes", "seedless grapes"]),
  produce("watermelon", undefined, ["seedless watermelon"]),
  produce("rockmelon", undefined, ["cantaloupe", "melon"]),
  produce("honeydew melon", undefined, ["honeydew"]),
  produce("kiwifruit", "kiwifruit", ["kiwi", "kiwis", "kiwi fruit"]),
  produce("passionfruit", "passionfruit", ["passion fruit", "passionfruits", "passionfruit pulp"]),
  produce("pomegranate", "pomegranates", ["pomegranate seeds", "pomegranate arils"]),
  produce("peach", "peaches", ["yellow peach", "yellow peaches", "white peach", "white peaches"]),
  produce("nectarine", "nectarines"),
  produce("plum", "plums"),
  produce("apricot", "apricots", ["fresh apricots"]),
  produce("fig", "figs", ["fresh figs"]),
  produce("rhubarb"),
  produce("papaya", undefined, ["pawpaw", "red papaya"]),
  produce("lychee", "lychees"),
  produce("coconut", "coconuts", ["fresh coconut", "young coconut"]),

  // ── Fruit & veg: chilled produce
  produce("firm tofu", undefined, ["tofu", "extra firm tofu", "extra-firm tofu"]),
  produce("silken tofu", undefined, ["soft tofu", "soft silken tofu"]),
  produce("fried tofu puffs", undefined, ["tofu puffs"]),
  produce("tempeh"),

  // ── Bakery
  bakery("bread", undefined, ["white bread", "sandwich bread", "bread slices", "loaf of bread"]),
  bakery("sourdough", undefined, ["sourdough bread", "sourdough loaf", "sourdough slices"]),
  bakery("crusty bread", undefined, ["crusty bread rolls"]),
  bakery("wholemeal bread", undefined, ["whole wheat bread", "wholegrain bread", "multigrain bread", "brown bread"]),
  bakery("rye bread", undefined, ["dark rye bread", "rye"]),
  bakery("ciabatta", undefined, ["ciabatta loaf"]),
  bakery("baguette", "baguettes", ["french stick", "french bread", "french loaf"]),
  bakery("bread roll", "bread rolls", ["dinner roll", "dinner rolls", "crusty roll", "crusty rolls"]),
  bakery("burger bun", "burger buns", ["brioche burger bun", "brioche burger buns", "hamburger bun", "hamburger buns", "brioche bun", "brioche buns"]),
  bakery("hot dog roll", "hot dog rolls", ["hot dog bun", "hot dog buns"]),
  bakery("brioche", undefined, ["brioche loaf"]),
  bakery("pita bread", undefined, ["pita breads", "pitta breads", "pita", "pitta bread", "pitta", "pita pocket", "pita pockets", "lebanese bread"]),
  bakery("flatbread", "flatbreads", ["flat bread"]),
  bakery("naan", undefined, ["naan bread", "naan breads"]),
  bakery("flour tortilla", "flour tortillas", ["soft flour tortillas", "tortilla", "tortillas", "wrap", "wraps", "soft tortillas"]),
  bakery("corn tortilla", "corn tortillas", ["white corn tortillas", "yellow corn tortillas"]),
  bakery("english muffin", "english muffins"),
  bakery("croissant", "croissants"),
  bakery("pizza base", "pizza bases"),
  bakery("breadcrumbs", undefined, ["bread crumbs", "dried breadcrumbs", "dry breadcrumbs", "fresh breadcrumbs", "stale breadcrumbs", "fine breadcrumbs"]),
  bakery("panko breadcrumbs", undefined, ["panko", "panko crumbs", "japanese breadcrumbs"]),

  // ── Deli
  deli("bacon", undefined, [
    "bacon rashers",
    "bacon rasher",
    "streaky bacon",
    "middle bacon",
    "short cut bacon",
    "shortcut bacon",
    "rindless bacon",
    "bacon slices",
    "smoked bacon",
    "smoked streaky bacon",
    "bacon strips",
    "bacon lardons",
    "lardons",
  ]),
  deli("pancetta"),
  deli("prosciutto", undefined, ["parma ham", "prosciutto slices"]),
  deli("ham", undefined, ["leg ham", "sliced ham", "shaved ham", "smoked ham"]),
  deli("ham hock", "ham hocks", ["smoked ham hock", "pork hock", "pork hocks"]),
  deli("chorizo", undefined, ["chorizo sausage", "chorizo sausages", "cured chorizo"]),
  deli("salami", undefined, ["hot salami"]),
  deli("pepperoni"),
  deli("mortadella"),
  deli("guacamole", undefined, ["avocado dip"]),
  deli("fresh pasta", undefined, ["fresh lasagne sheets", "fresh egg pasta"]),
  deli("potato gnocchi", undefined, ["gnocchi"]),
  deli("hummus", undefined, ["houmous", "hommus"]),
  deli("pesto", undefined, ["basil pesto", "store-bought pesto"]),
  deli("kalamata olives", undefined, ["kalamata olive", "pitted kalamata olives"]),

  // ── Butcher: chicken
  butcher("chicken", undefined, ["cooked chicken", "shredded chicken", "leftover chicken"]),
  butcher("whole chicken", "whole chickens", ["free-range chicken", "roasting chicken"]),
  butcher("barbecue chicken", "barbecue chickens", ["bbq chicken", "roast chicken", "rotisserie chicken", "barbecued chicken"]),
  butcher("chicken thigh", "chicken thighs", [
    "chicken thigh fillet",
    "chicken thigh fillets",
    "free-range chicken thighs",
    "boneless chicken thighs",
    "skinless chicken thighs",
    "chicken thigh cutlet",
    "chicken thigh cutlets",
  ]),
  butcher("chicken breast", "chicken breasts", ["chicken breast fillet", "chicken breast fillets", "free-range chicken breasts", "chicken breast halves"]),
  butcher("chicken drumstick", "chicken drumsticks", ["drumstick", "drumsticks"]),
  butcher("chicken wing", "chicken wings", ["chicken wingettes", "wingettes"]),
  butcher("chicken maryland", "chicken marylands", ["chicken leg quarter", "chicken leg quarters", "chicken leg", "chicken legs"]),
  butcher("chicken tenderloin", "chicken tenderloins", ["chicken tenders", "chicken mini fillets"]),
  butcher("chicken mince", undefined, ["ground chicken", "minced chicken"]),

  // ── Butcher: beef
  butcher("beef", undefined, ["beef pieces"]),
  butcher("beef mince", undefined, [
    "hamburger",
    "hamburger mince",
    "minced beef",
    "ground beef",
    "lean beef mince",
    "premium beef mince",
    "hamburger meat",
    "ground chuck",
  ]),
  butcher("beef chuck", undefined, [
    "stew meat",
    "stewing steak",
    "chuck steak",
    "chuck beef",
    "chuck roast",
    "beef chuck steak",
    "stewing beef",
    "braising beef",
    "beef stewing steak",
  ]),
  butcher("gravy beef", undefined, ["beef shin", "shin beef", "beef shank"]),
  butcher("beef brisket", undefined, ["brisket"]),
  butcher("beef cheeks", undefined, ["beef cheek"]),
  butcher("beef short ribs", undefined, ["short ribs", "beef short rib"]),
  butcher("oxtail"),
  butcher("rump steak", "rump steaks", ["beef rump", "beef rump steak", "rump"]),
  butcher("sirloin steak", "sirloin steaks", ["porterhouse steak", "porterhouse steaks", "new york strip steak", "beef sirloin", "sirloin"]),
  butcher("scotch fillet", "scotch fillets", [
    "scotch fillet steak",
    "scotch fillet steaks",
    "rib eye",
    "rib eye steak",
    "rib eye steaks",
    "ribeye",
    "ribeye steak",
    "ribeye steaks",
  ]),
  butcher("eye fillet", "eye fillets", ["beef eye fillet", "beef fillet", "beef tenderloin", "fillet steak", "fillet steaks"]),
  butcher("flank steak", undefined, ["skirt steak", "flap meat"]),
  butcher("beef stir-fry strips", undefined, ["beef strips", "stir-fry beef", "beef stir fry strips"]),
  butcher("steak", "steaks", ["beef steak", "beef steaks"]),
  butcher("roast beef", undefined, ["beef roast", "topside roast", "silverside"]),
  butcher("corned beef", undefined, ["corned silverside"]),

  // ── Butcher: pork, lamb and the rest
  butcher("pork", undefined, ["pork pieces"]),
  butcher("pork mince", undefined, ["pork and veal mince", "pork & veal mince", "minced pork", "ground pork"]),
  butcher("sausage mince", undefined, ["sausagemeat", "sausage meat"]),
  butcher("pork belly", undefined, ["pork belly slices", "pork belly strips", "boneless pork belly"]),
  butcher("pork shoulder", undefined, ["pork butt", "boston butt", "pork scotch", "pork neck", "pork collar"]),
  butcher("pork loin", undefined, ["pork loin roast", "boneless pork loin"]),
  butcher("pork fillet", "pork fillets", ["pork tenderloin", "pork tenderloins"]),
  butcher("pork chop", "pork chops", ["pork cutlet", "pork cutlets", "pork loin chops", "pork loin steaks", "pork steaks"]),
  butcher("pork ribs", undefined, ["pork spare ribs", "spare ribs", "baby back ribs", "pork rib"]),
  butcher("sausage", "sausages", [
    "chicken sausage",
    "chicken sausages",
    "lamb sausages",
    "smoked sausage",
    "kielbasa",
    "polish sausage",
    "frankfurters",
    "frankfurter",
    "frankfurts",
    "hot dogs",
    "pork sausage",
    "pork sausages",
    "beef sausage",
    "beef sausages",
    "thin sausages",
    "thick sausages",
  ]),
  butcher("italian sausage", "italian sausages", ["italian pork sausages", "fennel sausages"]),
  butcher("lamb", undefined, ["lamb pieces"]),
  butcher("lamb mince", undefined, ["minced lamb", "ground lamb"]),
  butcher("lamb shoulder", undefined, ["lamb shoulder roast", "boneless lamb shoulder"]),
  butcher("lamb leg", undefined, ["leg of lamb", "lamb leg roast", "butterflied lamb leg", "boneless lamb leg"]),
  butcher("lamb shank", "lamb shanks", ["frenched lamb shanks"]),
  butcher("lamb cutlet", "lamb cutlets", ["frenched lamb cutlets"]),
  butcher("lamb chop", "lamb chops", ["lamb loin chop", "lamb loin chops", "lamb forequarter chops"]),
  butcher("lamb rack", "lamb racks", ["rack of lamb", "racks of lamb", "frenched lamb rack"]),
  butcher("lamb backstrap", "lamb backstraps", ["lamb loin", "lamb fillet", "lamb fillets"]),
  butcher("veal", undefined, ["veal schnitzel", "veal steaks"]),
  butcher("turkey", undefined, ["turkey breast", "whole turkey"]),
  butcher("turkey mince", undefined, ["ground turkey", "minced turkey"]),
  butcher("duck breast", "duck breasts", ["duck breast fillets"]),
  butcher("duck", undefined, ["whole duck", "duck legs", "duck leg"]),
  butcher("kangaroo fillet", "kangaroo fillets", ["kangaroo", "kangaroo steaks"]),

  // ── Seafood
  seafood("prawn", "prawns", [
    "green prawn",
    "green prawns",
    "raw prawn",
    "raw prawns",
    "king prawn",
    "king prawns",
    "tiger prawn",
    "tiger prawns",
    "peeled prawns",
    "cooked prawns",
    "shrimp",
    "shrimps",
    "large shrimp",
    "raw shrimp",
  ]),
  seafood("salmon fillet", "salmon fillets", ["side of salmon", "salmon", "skinless salmon fillets", "salmon portions", "atlantic salmon"]),
  seafood("ocean trout fillet", "ocean trout fillets", ["ocean trout", "trout fillet", "trout fillets", "trout"]),
  seafood("smoked salmon", undefined, ["smoked salmon slices", "hot-smoked salmon", "lox"]),
  seafood("white fish fillet", "white fish fillets", [
    "firm white fish fillet",
    "firm white fish fillets",
    "white fish",
    "fish fillet",
    "fish fillets",
    "boneless white fish fillets",
  ]),
  seafood("barramundi fillet", "barramundi fillets", ["barramundi"]),
  seafood("snapper fillet", "snapper fillets", ["snapper", "whole snapper"]),
  seafood("flathead fillet", "flathead fillets", ["flathead"]),
  seafood("ling fillet", "ling fillets", ["ling"]),
  seafood("cod fillet", "cod fillets", ["cod"]),
  seafood("mussels", undefined, ["mussel", "black mussels", "pot-ready mussels"]),
  seafood("clams", undefined, ["clam", "vongole", "pipis"]),
  seafood("squid", undefined, ["cuttlefish", "calamari", "squid tubes", "calamari rings", "squid rings", "baby squid"]),
  seafood("octopus", undefined, ["baby octopus"]),
  seafood("scallop", "scallops", ["scallop meat", "sea scallops"]),
  seafood("crab meat", undefined, ["crabmeat", "crab", "blue swimmer crab"]),
  seafood("oyster", "oysters", ["fresh oysters"]),
  seafood("lobster", undefined, ["rock lobster", "lobster tails"]),

  // ── Dairy & eggs
  dairy("egg", "eggs", [
    "free-range egg",
    "free-range eggs",
    "free range egg",
    "free range eggs",
    "whole egg",
    "whole eggs",
    "large egg",
    "large eggs",
    "hard-boiled egg",
    "hard-boiled eggs",
    "boiled egg",
    "boiled eggs",
  ]),
  dairy("egg yolk", "egg yolks", ["yolk", "yolks", "free-range egg yolks", "large egg yolks"]),
  dairy("egg white", "egg whites", ["free-range egg whites", "large egg whites"]),
  dairy("butter", undefined, ["salted butter", "softened butter", "melted butter", "cold butter", "chilled butter"]),
  dairy("unsalted butter", undefined, []),
  dairy("ghee", undefined, ["clarified butter"]),
  dairy("duck fat", undefined, ["goose fat", "lard", "beef dripping", "dripping"]),
  dairy("margarine", undefined, ["oleo", "vegan butter", "plant-based butter", "dairy-free spread", "baking spread", "olive oil spread"]),
  dairy("milk", undefined, [
    "full fat milk",
    "full-fat milk",
    "full-cream milk",
    "full cream milk",
    "whole milk",
    "semi-skimmed milk",
    "reduced-fat milk",
    "light milk",
    "low-fat milk",
    "warm milk",
    "cold milk",
    "fresh milk",
  ]),
  dairy("skim milk", undefined, ["skimmed milk", "no-fat milk"]),
  dairy("buttermilk"),
  dairy("thickened cream", undefined, [
    "heavy cream",
    "whipping cream",
    "heavy whipping cream",
    "thickened heavy cream",
    "heavy thickened cream",
    "thickened or heavy cream",
  ]),
  dairy("pure cream", undefined, ["pouring cream", "cream", "single cream", "light cream", "fresh cream", "pure pouring cream"]),
  dairy("double cream", undefined, ["thick cream", "dollop cream", "clotted cream"]),
  dairy("sour cream", undefined, ["soured cream", "light sour cream"]),
  dairy("crème fraîche", undefined, ["creme fraiche", "crème fraiche", "creme fraîche"]),
  dairy("cream cheese", undefined, [
    "soft cheese",
    "full-fat soft cheese",
    "light soft cheese",
    "philadelphia cream cheese",
    "spreadable cream cheese",
    "light cream cheese",
  ]),
  dairy("mascarpone", undefined, ["mascarpone cheese"]),
  dairy("ricotta", undefined, ["ricotta cheese", "fresh ricotta", "firm ricotta", "smooth ricotta", "whole-milk ricotta"]),
  dairy("cottage cheese"),
  dairy("greek yoghurt", undefined, [
    "thick yoghurt",
    "thick greek yogurt",
    "thick greek-style yogurt",
    "thick natural yogurt",
    "greek yogurt",
    "greek-style yoghurt",
    "greek-style yogurt",
    "greek style yoghurt",
    "thick greek yoghurt",
  ]),
  dairy("natural yoghurt", undefined, [
    "yoghurt",
    "yogurt",
    "plain yoghurt",
    "plain yogurt",
    "natural yogurt",
    "unsweetened yoghurt",
    "plain greek yoghurt",
    "fat-free natural yoghurt",
    "low-fat natural yoghurt",
  ]),
  dairy("parmesan", undefined, [
    "freshly grated parmesan",
    "freshly grated parmesan cheese",
    "vegetarian italian-style hard cheese",
    "parmesan cheese",
    "parmigiano reggiano",
    "parmigiano-reggiano",
    "grated parmesan",
    "finely grated parmesan",
    "shaved parmesan",
    "parmesan shavings",
    "vegetarian parmesan",
    "parmesan rind",
  ]),
  dairy("pecorino", undefined, ["pecorino romano", "pecorino cheese"]),
  dairy("cheddar", undefined, [
    "cheddar cheese",
    "tasty cheese",
    "grated tasty cheese",
    "sharp cheddar",
    "mature cheddar",
    "vintage cheddar",
    "cheese",
    "grated cheese",
    "shredded cheese",
    "grated cheddar",
    "grated cheddar cheese",
  ]),
  dairy("mozzarella", undefined, [
    "mozzarella cheese",
    "grated mozzarella",
    "shredded mozzarella",
    "fresh mozzarella",
    "buffalo mozzarella",
    "ball of mozzarella",
  ]),
  dairy("pizza cheese", undefined, ["pizza cheese blend", "grated pizza cheese"]),
  dairy("bocconcini", undefined, ["baby bocconcini", "cherry bocconcini"]),
  dairy("burrata"),
  dairy("feta", undefined, ["fetta", "feta cheese", "fetta cheese", "danish feta", "persian feta", "marinated feta", "greek feta", "crumbled feta"]),
  dairy("haloumi", undefined, ["halloumi", "halloumi cheese", "haloumi cheese"]),
  dairy("goat's cheese", undefined, ["goats cheese", "goat cheese", "soft goat's cheese", "chèvre", "chevre"]),
  dairy("blue cheese", undefined, ["gorgonzola", "stilton", "roquefort", "danish blue"]),
  dairy("brie", undefined, ["brie cheese", "camembert"]),
  dairy("gruyère", undefined, ["gruyere", "gruyère cheese", "gruyere cheese", "swiss cheese", "emmental", "comté", "comte"]),
  dairy("american cheese", undefined, ["cheese slices", "sliced cheese", "processed cheese", "burger cheese"]),
  dairy("monterey jack", undefined, ["monterey jack cheese", "pepper jack", "jack cheese"]),
  dairy("paneer"),
  dairy("red leicester", undefined, ["red leicester cheese", "double gloucester"]),
  dairy("custard", undefined, ["vanilla custard", "store-bought custard", "thick custard"]),

  // ── Pantry: oils and vinegars
  pantry("olive oil", undefined, ["light olive oil", "mild olive oil", "pure olive oil", "regular olive oil"]),
  pantry("extra virgin olive oil", undefined, ["virgin olive oil", "extra-virgin olive oil", "evoo", "good olive oil", "best-quality extra virgin olive oil"]),
  pantry("vegetable oil", undefined, [
    "salad oil",
    "vegetable or sunflower oil",
    "sunflower or vegetable oil",
    "neutral-tasting oil",
    "vegetable or olive oil",
    "oil",
    "neutral oil",
    "cooking oil",
    "flavourless oil",
    "flavorless oil",
    "neutral-flavoured oil",
    "neutral flavoured oil",
    "vegetable or canola oil",
    "oil for frying",
  ]),
  pantry("canola oil", undefined, ["cold-pressed rapeseed oil", "rapeseed oil"]),
  pantry("sunflower oil"),
  pantry("peanut oil", undefined, ["groundnut oil"]),
  pantry("rice bran oil"),
  pantry("grapeseed oil", undefined, ["grape seed oil"]),
  pantry("coconut oil", undefined, ["virgin coconut oil", "extra virgin coconut oil"]),
  pantry("sesame oil", undefined, ["toasted sesame oil", "pure sesame oil"]),
  pantry("avocado oil"),
  pantry("cooking spray", undefined, [
    "spray oil",
    "oil spray",
    "cooking oil spray",
    "olive oil spray",
    "canola oil spray",
    "oil cooking spray",
    "cooking-oil spray",
    "non-stick cooking spray",
  ]),
  pantry("balsamic vinegar", undefined, ["balsamic"]),
  pantry("balsamic glaze", undefined, ["balsamic reduction"]),
  pantry("white balsamic vinegar", undefined, ["white balsamic"]),
  pantry("red wine vinegar"),
  pantry("white wine vinegar", undefined, ["red or white wine vinegar", "champagne vinegar"]),
  pantry("apple cider vinegar", undefined, ["cider vinegar"]),
  pantry("white vinegar", undefined, ["vinegar", "distilled vinegar", "distilled white vinegar", "plain vinegar"]),
  pantry("sherry vinegar", undefined, ["jerez vinegar"]),
  pantry("malt vinegar"),

  // ── Pantry: stocks and tins
  pantry("chicken stock", undefined, [
    "chicken or vegetable stock",
    "chicken or beef stock",
    "organic chicken stock",
    "chicken broth",
    "low-sodium chicken stock",
    "salt-reduced chicken stock",
    "reduced-salt chicken stock",
    "low sodium chicken broth",
    "homemade chicken stock",
  ]),
  pantry("chicken stock cube", "chicken stock cubes", [
    "chicken bouillon cube",
    "chicken bouillon cubes",
    "chicken stock powder",
    "chicken bouillon",
    "chicken bouillon powder",
  ]),
  pantry("beef stock", undefined, ["beef broth", "salt-reduced beef stock", "low-sodium beef stock", "beef consommé", "beef consomme"]),
  pantry("beef stock cube", "beef stock cubes", ["beef bouillon cube", "beef bouillon cubes", "beef stock powder", "beef bouillon", "beef bouillon powder"]),
  pantry("vegetable stock", undefined, [
    "organic vegetable stock",
    "vegetable broth",
    "veg stock",
    "salt-reduced vegetable stock",
    "low-sodium vegetable stock",
  ]),
  pantry("vegetable stock cube", "vegetable stock cubes", [
    "vegetable bouillon cube",
    "vegetable bouillon cubes",
    "vegetable stock powder",
    "vegetable bouillon powder",
  ]),
  pantry("fish stock", undefined, ["fish broth", "seafood stock"]),
  pantry("canned tomatoes", undefined, [
    "stewed tomatoes",
    "diced tomatoes",
    "crushed tomatoes",
    "chopped tomatoes",
    "tinned tomatoes",
    "canned diced tomatoes",
    "canned crushed tomatoes",
    "crushed canned tomatoes",
    "diced canned tomatoes",
    "tinned chopped tomatoes",
    "chopped tinned tomatoes",
    "tinned diced tomatoes",
    "whole peeled tomatoes",
    "peeled tomatoes",
    "canned whole tomatoes",
  ]),
  pantry("canned cherry tomatoes", undefined, ["tinned cherry tomatoes"]),
  pantry("tomato paste", undefined, ["tomato purée", "tomato puree", "concentrated tomato paste", "double concentrated tomato paste"]),
  pantry("passata", undefined, ["tomato passata", "tomato sugo", "sugo", "strained tomatoes"]),
  pantry("sun-dried tomatoes", undefined, ["sundried tomatoes", "sun dried tomatoes", "semi-dried tomatoes", "sun-dried tomato"]),
  pantry("chickpeas", undefined, ["chickpea", "canned chickpeas", "tinned chickpeas", "garbanzo beans", "dried chickpeas"]),
  pantry("cannellini beans", undefined, [
    "cannellini bean",
    "white beans",
    "canned cannellini beans",
    "white cannellini beans",
    "great northern beans",
    "navy beans",
    "haricot beans",
  ]),
  pantry("butter beans", undefined, ["butter bean", "lima beans", "lima bean", "canned butter beans"]),
  pantry("kidney beans", undefined, ["red kidney beans", "kidney bean", "canned kidney beans"]),
  pantry("black beans", undefined, ["black bean", "canned black beans", "black turtle beans"]),
  pantry("borlotti beans", undefined, ["borlotti bean", "pinto beans", "pinto bean"]),
  pantry("four bean mix", undefined, ["mixed beans", "three bean mix"]),
  pantry("baked beans", undefined, ["baked beans in tomato sauce"]),
  pantry("cream of mushroom soup", undefined, ["condensed cream of mushroom soup", "mushroom soup"]),
  pantry("cream of chicken soup", undefined, ["condensed cream of chicken soup"]),
  pantry("applesauce", undefined, ["apple sauce", "unsweetened applesauce", "apple puree", "apple purée"]),
  pantry("fruit cocktail", undefined, ["canned fruit salad", "tinned fruit salad", "fruit salad in juice"]),
  pantry("croutons", undefined, ["seasoned croutons"]),
  pantry("brown lentils", undefined, ["lentils", "canned lentils", "tinned lentils", "brown lentil"]),
  pantry("red lentils", undefined, ["red split lentils", "split red lentils", "red lentil", "masoor dal"]),
  pantry("green lentils", undefined, ["french green lentils", "puy lentils", "french lentils", "du puy lentils", "puy-style lentils"]),
  pantry("yellow split peas", undefined, ["split peas", "chana dal", "toor dal"]),
  pantry("corn kernels", undefined, [
    "whole kernel corn",
    "kernel corn",
    "frozen sweetcorn",
    "corn",
    "sweetcorn",
    "sweet corn",
    "canned corn",
    "canned corn kernels",
    "frozen corn",
    "frozen corn kernels",
    "tinned sweetcorn",
  ]),
  pantry("creamed corn", undefined, ["cream-style corn", "cream style corn"]),
  pantry("canned beetroot", undefined, ["tinned beetroot", "sliced beetroot"]),
  pantry("tuna", undefined, ["canned tuna", "tinned tuna", "tuna in oil", "tuna in springwater", "tuna chunks"]),
  pantry("canned salmon", undefined, ["tinned salmon", "red salmon", "pink salmon"]),
  pantry("anchovy fillet", "anchovy fillets", ["anchovy", "anchovies", "anchovies in oil"]),
  pantry("sardines", undefined, ["sardine", "canned sardines"]),
  pantry("coconut milk", undefined, ["light coconut milk", "canned coconut milk", "full-fat coconut milk", "reduced-fat coconut milk", "tinned coconut milk"]),
  pantry("coconut cream", undefined, ["light coconut cream", "canned coconut cream"]),
  pantry("evaporated milk", undefined, ["light evaporated milk", "evaporated skim milk"]),
  pantry("sweetened condensed milk", undefined, ["eagle brand milk", "sweetened condensed", "condensed milk", "can condensed milk"]),
  pantry("artichoke hearts", undefined, ["marinated artichoke hearts", "artichoke heart", "canned artichoke hearts"]),
  pantry("roasted capsicum", undefined, [
    "pimento",
    "pimentos",
    "pimiento",
    "pimientos",
    "roasted peeled red peppers",
    "jarred roasted red peppers",
    "char-grilled capsicum",
    "roasted red capsicum",
    "roasted red peppers",
    "roasted red pepper",
    "chargrilled capsicum",
    "roasted peppers",
    "jarred roasted peppers",
  ]),
  pantry("black olives", undefined, ["black olive", "pitted black olives"]),
  pantry("green olives", undefined, ["green olive", "pitted green olives", "sicilian olives", "castelvetrano olives"]),
  pantry("olives", undefined, ["olive", "mixed olives", "pitted olives"]),
  pantry("capers", undefined, ["baby capers", "caper", "capers in brine", "salted capers"]),
  pantry("gherkins", undefined, ["gherkin", "dill pickles", "dill pickle", "pickles", "pickle", "cornichons", "cornichon"]),
  pantry("pickled jalapeños", undefined, ["pickled jalapenos", "jarred jalapeños", "jarred jalapenos"]),
  pantry("sauerkraut"),
  pantry("water chestnuts", undefined, ["canned water chestnuts", "water chestnut"]),
  pantry("bamboo shoots", undefined, ["canned bamboo shoots"]),

  // ── Pantry: sauces and condiments
  pantry("tomato sauce", undefined, ["ketchup", "tomato ketchup", "catsup"]),
  pantry("barbecue sauce", undefined, ["bbq sauce", "barbeque sauce", "smoky barbecue sauce"]),
  pantry("worcestershire sauce", undefined, ["worcestershire", "worcester sauce"]),
  pantry("hot sauce", undefined, ["tabasco", "tabasco sauce", "louisiana hot sauce", "chilli hot sauce"]),
  pantry("sweet chilli sauce", undefined, ["sweet chili sauce", "thai sweet chilli sauce"]),
  pantry("sriracha", undefined, ["sriracha sauce", "sriracha chilli sauce"]),
  pantry("chilli sauce", undefined, ["chili sauce", "hot chilli sauce", "chilli garlic sauce"]),
  pantry("mayonnaise", undefined, ["mayo", "whole-egg mayonnaise", "whole egg mayonnaise", "egg mayonnaise", "light mayonnaise"]),
  pantry("kewpie mayonnaise", undefined, ["kewpie mayo", "japanese mayonnaise", "japanese mayo"]),
  pantry("aioli", undefined, ["garlic aioli", "garlic mayonnaise"]),
  pantry("dijon mustard", undefined, ["dijon"]),
  pantry("wholegrain mustard", undefined, ["whole grain mustard", "seeded mustard", "grainy mustard", "wholegrain dijon mustard"]),
  pantry("american mustard", undefined, ["yellow mustard", "prepared mustard", "mild mustard"]),
  pantry("english mustard", undefined, ["hot english mustard"]),
  pantry("horseradish", undefined, ["horseradish cream", "prepared horseradish", "creamed horseradish", "fresh horseradish"]),
  pantry("mint sauce", undefined, ["mint jelly"]),
  pantry("tartare sauce", undefined, ["tartar sauce"]),
  pantry("cranberry sauce", undefined, ["cranberry jelly"]),
  pantry("chutney", undefined, ["sweet pickle relish", "pickle relish", "tomato chutney", "fruit chutney", "tomato relish", "relish"]),
  pantry("mango chutney"),
  pantry("marmalade", undefined, ["orange marmalade", "seville orange marmalade"]),
  pantry("vegemite", undefined, ["marmite", "yeast extract"]),
  pantry("pasta sauce", undefined, ["tomato pasta sauce", "bottled tomato pasta sauce", "marinara sauce", "jarred pasta sauce", "napoletana sauce"]),
  pantry("pizza sauce", undefined, ["pizza base sauce"]),
  pantry("salsa", undefined, ["picante sauce", "tomato salsa", "jarred salsa", "chunky salsa"]),
  pantry("tahini", undefined, ["hulled tahini", "unhulled tahini", "tahini paste"]),
  pantry("peanut butter", undefined, ["smooth peanut butter", "crunchy peanut butter", "natural peanut butter", "creamy peanut butter"]),
  pantry("chocolate hazelnut spread", undefined, ["nutella"]),
  pantry("jam", undefined, ["fruit jam", "jam of your choice"]),
  pantry("strawberry jam", undefined, ["strawberry preserves", "strawberry conserve"]),
  pantry("raspberry jam", undefined, ["raspberry preserves", "raspberry conserve"]),
  pantry("apricot jam", undefined, ["apricot preserves", "apricot conserve"]),
  pantry("lemon curd", undefined, ["lemon butter"]),
  pantry("honey", undefined, ["runny honey", "raw honey", "clear honey", "pure honey"]),
  pantry("maple syrup", undefined, ["pure maple syrup", "real maple syrup"]),
  pantry("golden syrup", undefined, ["light treacle"]),
  pantry("treacle", undefined, ["black treacle", "molasses", "blackstrap molasses"]),
  pantry("rice malt syrup", undefined, ["brown rice syrup"]),
  pantry("marzipan", undefined, ["almond paste"]),
  pantry("preserved lemon", "preserved lemons", ["preserved lemon rind"]),
  pantry("pomegranate molasses", undefined, ["pomegranate syrup"]),
  pantry("liquid smoke"),
  pantry("truffle oil"),
  pantry("dried porcini mushrooms", undefined, ["dried porcini", "porcini mushrooms", "porcini"]),
  pantry("dried shiitake mushrooms", undefined, ["dried shiitake", "dried shiitake mushroom", "dried chinese mushrooms"]),

  // ── Pantry: pasta, rice, grains and noodles
  pantry("pasta", undefined, ["dried pasta", "short pasta", "pasta of choice", "pasta of your choice"]),
  pantry("spaghetti", undefined, ["dried spaghetti", "spaghetti pasta", "thin spaghetti"]),
  pantry("spaghettini"),
  pantry("linguine", undefined, ["linguini"]),
  pantry("fettuccine", undefined, ["fettucine", "fettuccini"]),
  pantry("tagliatelle"),
  pantry("pappardelle", undefined, ["dried pappardelle"]),
  pantry("angel hair pasta", undefined, ["angel hair", "capellini"]),
  pantry("penne", undefined, ["penne pasta", "penne rigate"]),
  pantry("rigatoni", undefined, ["rigatoni pasta"]),
  pantry("fusilli", undefined, ["fusilli pasta", "spiral pasta", "spirals", "rotini"]),
  pantry("macaroni", undefined, ["elbow macaroni", "macaroni pasta", "elbow pasta"]),
  pantry("orecchiette"),
  pantry("farfalle", undefined, ["bow tie pasta", "bowtie pasta", "bow ties"]),
  pantry("pasta shells", undefined, ["conchiglie", "shell pasta", "small pasta shells", "large pasta shells", "conchiglioni"]),
  pantry("risoni", undefined, ["orzo", "risoni pasta", "orzo pasta"]),
  pantry("lasagne sheets", undefined, ["lasagne", "lasagna sheets", "lasagna noodles", "lasagne noodles", "dried lasagne sheets", "instant lasagne sheets"]),
  pantry("cannelloni tubes", undefined, ["cannelloni", "manicotti"]),
  pantry("egg noodles", undefined, ["noodles", "wide egg noodles", "dried egg noodles", "fresh egg noodles", "thin egg noodles", "chow mein noodles"]),
  pantry("hokkien noodles", undefined, ["fresh hokkien noodles", "hokkien"]),
  pantry("rice noodles", undefined, [
    "flat rice noodles",
    "dried rice noodles",
    "rice stick noodles",
    "pad thai noodles",
    "fresh rice noodles",
    "wide rice noodles",
  ]),
  pantry("rice vermicelli", undefined, ["vermicelli noodles", "rice vermicelli noodles", "vermicelli rice noodles", "vermicelli", "thin rice noodles"]),
  pantry("glass noodles", undefined, ["bean thread noodles", "cellophane noodles", "mung bean noodles", "bean vermicelli"]),
  pantry("udon noodles", undefined, ["udon", "fresh udon noodles"]),
  pantry("soba noodles", undefined, ["soba", "buckwheat noodles"]),
  pantry("ramen noodles", undefined, ["ramen", "instant noodles", "instant ramen noodles"]),
  pantry("white rice", undefined, [
    "instant rice",
    "minute rice",
    "rice",
    "long grain rice",
    "long-grain rice",
    "long grain white rice",
    "long-grain white rice",
    "white long-grain rice",
    "medium grain rice",
    "medium-grain rice",
    "cooked rice",
    "steamed rice",
    "cooked white rice",
    "steamed white rice",
    "uncooked rice",
  ]),
  pantry("jasmine rice", undefined, ["steamed jasmine rice", "cooked jasmine rice", "thai jasmine rice"]),
  pantry("basmati rice", undefined, ["cooked basmati rice", "steamed basmati rice"]),
  pantry("arborio rice", undefined, ["risotto rice", "carnaroli rice", "carnaroli"]),
  pantry("brown rice", undefined, ["brown basmati rice", "cooked brown rice", "long grain brown rice"]),
  pantry("sushi rice", undefined, ["short grain rice", "short-grain rice", "calrose rice", "japanese rice"]),
  pantry("glutinous rice", undefined, ["sticky rice", "sweet rice"]),
  pantry("wild rice", undefined, ["wild rice blend"]),
  pantry("couscous", undefined, ["wholewheat couscous", "whole wheat couscous", "instant couscous", "wholemeal couscous"]),
  pantry("pearl couscous", undefined, ["israeli couscous", "giant couscous", "moghrabieh"]),
  pantry("quinoa", undefined, ["white quinoa", "red quinoa", "tri-colour quinoa", "cooked quinoa"]),
  pantry("bulgur", undefined, ["burghul", "bulgur wheat", "cracked wheat", "bulghur"]),
  pantry("pearl barley", undefined, ["barley"]),
  pantry("freekeh"),
  pantry("polenta", undefined, ["quick-cook polenta", "quick-cooking polenta", "instant polenta", "cornmeal", "corn meal", "yellow cornmeal", "fine polenta"]),
  pantry("rolled oats", undefined, [
    "rolled porridge oats",
    "oats",
    "porridge oats",
    "old-fashioned oats",
    "old fashioned oats",
    "quick oats",
    "quick-cooking oats",
    "instant oats",
    "oatmeal",
    "jumbo oats",
  ]),
  pantry("cornflakes", undefined, ["corn flakes"]),
  pantry("rice bubbles", undefined, ["rice krispies", "puffed rice"]),

  // ── Pantry: nuts, seeds and dried fruit
  pantry("almonds", undefined, ["almond", "whole almonds", "raw almonds", "natural almonds", "almond kernels", "roasted almonds", "toasted almonds"]),
  pantry("slivered almonds", undefined, ["slivered almond"]),
  pantry("flaked almonds", undefined, ["flaked almond", "sliced almonds"]),
  pantry("blanched almonds", undefined, ["blanched almond"]),
  pantry("walnuts", undefined, ["shelled walnuts", "walnut", "walnut halves", "walnut pieces", "chopped walnuts"]),
  pantry("pecans", undefined, ["pecan", "pecan halves", "pecan nuts", "pecan pieces"]),
  pantry("cashews", undefined, ["cashew", "cashew nuts", "raw cashews", "roasted cashews", "unsalted cashews"]),
  pantry("pistachios", undefined, [
    "unsalted pistachios",
    "shelled unsalted pistachios",
    "pistachio",
    "pistachio kernels",
    "pistachio nuts",
    "shelled pistachios",
  ]),
  pantry("hazelnuts", undefined, ["hazelnut", "roasted hazelnuts", "blanched hazelnuts", "hazelnut kernels"]),
  pantry("macadamias", undefined, ["macadamia", "macadamia nuts", "macadamia nut"]),
  pantry("pine nuts", undefined, ["toasted pine nuts", "pine nut", "pinenuts", "pignoli"]),
  pantry("peanuts", undefined, ["peanut", "roasted peanuts", "unsalted roasted peanuts", "roasted unsalted peanuts", "raw peanuts", "salted peanuts"]),
  pantry("brazil nuts", undefined, ["brazil nut"]),
  pantry("candlenuts", undefined, ["candlenut"]),
  pantry("mixed nuts", undefined, ["mixed unsalted nuts", "nuts"]),
  pantry("chestnuts", undefined, ["chestnut", "vac-packed chestnuts", "cooked chestnuts"]),
  pantry("sesame seeds", undefined, ["white sesame seeds", "toasted sesame seeds", "sesame seed", "white sesame seed"]),
  pantry("black sesame seeds", undefined, ["black sesame seed"]),
  pantry("sunflower seeds", undefined, ["sunflower seed", "sunflower kernels"]),
  pantry("pepitas", undefined, ["pumpkin seeds", "pepita", "pumpkin seed"]),
  pantry("chia seeds", undefined, ["chia seed", "chia"]),
  pantry("linseeds", undefined, ["linseed", "flaxseeds", "flaxseed", "flax seeds", "ground flaxseed", "flaxseed meal"]),
  pantry("poppy seeds", undefined, ["poppy seed", "poppyseeds", "poppyseed"]),
  pantry("raisins", undefined, ["raisin", "seedless raisins"]),
  pantry("sultanas", undefined, ["white raisins", "sultana", "golden raisins"]),
  pantry("currants", undefined, ["currant", "dried currants", "zante currants"]),
  pantry("dried cranberries", undefined, ["craisins", "sweetened dried cranberries"]),
  pantry("dried apricots", undefined, ["dried apricot", "dried apricot halves"]),
  pantry("dates", undefined, ["date", "medjool dates", "medjool date", "pitted dates", "dried dates", "fresh dates"]),
  pantry("prunes", undefined, ["prune", "pitted prunes"]),
  pantry("dried figs", undefined, ["dried fig"]),
  pantry("mixed dried fruit", undefined, ["mixed fruit", "dried mixed fruit", "dried fruit", "fruit medley"]),
  pantry("mixed peel", undefined, ["candied peel", "candied citrus peel", "mixed candied peel"]),
  pantry("glacé cherries", undefined, ["glace cherries", "candied cherries", "maraschino cherries"]),
  pantry("desiccated coconut", undefined, ["dessicated coconut", "unsweetened desiccated coconut"]),
  pantry("shredded coconut", undefined, ["shredded unsweetened coconut", "sweetened shredded coconut"]),
  pantry("coconut flakes", undefined, ["flaked coconut", "coconut chips", "toasted coconut flakes"]),

  // ── Pantry: breakfast and snacks
  pantry("tortilla chips", undefined, ["corn chips", "nacho chips"]),
  pantry("taco shells", undefined, ["taco shell", "hard taco shells"]),
  pantry("potato chips", undefined, ["crisps", "plain potato chips"]),
  pantry("water crackers", undefined, ["crackers", "cracker", "savoury crackers"]),

  // ── Baking
  baking("plain flour", undefined, [
    "flour",
    "all-purpose flour",
    "all purpose flour",
    "plain white flour",
    "plain all-purpose flour",
    "white flour",
    "flour for dusting",
    "sifted plain flour",
  ]),
  baking("self-raising flour", undefined, ["self raising flour", "self-rising flour", "self rising flour", "sr flour"]),
  baking("wholemeal flour", undefined, ["plain wholemeal flour", "whole wheat flour", "wholewheat flour", "wholemeal plain flour", "whole-wheat flour"]),
  baking("wholemeal self-raising flour", undefined, ["wholemeal self raising flour"]),
  baking("bread flour", undefined, ["strong plain flour", "strong white bread flour", "strong bread flour", "strong flour", "baker's flour", "bakers flour"]),
  baking("tipo 00 flour", undefined, ["tipo flour", "pasta flour", "type 00 flour"]),
  baking("gluten-free plain flour", undefined, ["gluten free plain flour", "gluten-free flour", "gluten free flour"]),
  baking("gluten-free self-raising flour", undefined, ["gluten free self-raising flour", "gluten free self raising flour"]),
  baking("rice flour", undefined, ["white rice flour"]),
  baking("glutinous rice flour", undefined, ["sweet rice flour", "mochiko"]),
  baking("chickpea flour", undefined, ["besan", "besan flour", "gram flour", "garbanzo flour"]),
  baking("almond meal", undefined, ["almond flour", "ground almonds", "blanched almond meal"]),
  baking("hazelnut meal", undefined, ["ground hazelnuts", "hazelnut flour"]),
  baking("coconut flour"),
  baking("cake flour", undefined, ["cake wheat flour"]),
  baking("shortening", undefined, ["vegetable shortening", "crisco", "solid vegetable shortening"]),
  baking("copha", undefined, ["solidified coconut oil"]),
  baking("jelly crystals", undefined, [
    "jelly",
    "jello",
    "jell-o",
    "raspberry jelly crystals",
    "strawberry jelly crystals",
    "lime jelly crystals",
    "jelly mix",
  ]),
  baking("cake mix", undefined, ["packet cake mix", "yellow cake mix", "white cake mix", "chocolate cake mix", "vanilla cake mix", "butter cake mix"]),
  baking("instant pudding mix", undefined, [
    "instant pudding",
    "instant vanilla pudding",
    "instant vanilla pudding mix",
    "vanilla pudding mix",
    "instant chocolate pudding",
  ]),
  baking("buckwheat flour"),
  baking("spelt flour", undefined, ["wholemeal spelt flour", "white spelt flour"]),
  baking("xanthan gum"),
  baking("fresh yeast", undefined, ["compressed yeast", "cake yeast"]),
  baking("sugar syrup", undefined, ["simple syrup"]),
  baking("dulce de leche", undefined, ["caramel", "caramel sauce", "salted caramel sauce"]),
  baking("whipped cream", undefined, ["whipped topping", "cool whip", "whipped thickened cream"]),
  baking("mixed seeds", undefined, ["seed mix", "mixed seed"]),
  baking("semolina", undefined, ["fine semolina", "coarse semolina", "semolina flour"]),
  baking("cornflour", undefined, ["cornstarch", "corn starch", "maize cornflour", "wheaten cornflour", "corn flour"]),
  baking("tapioca flour", undefined, ["tapioca starch", "arrowroot", "arrowroot powder", "potato starch", "potato flour"]),
  baking("baking powder", undefined, ["gluten-free baking powder", "gluten free baking powder", "double-acting baking powder"]),
  baking("bicarbonate of soda", undefined, [
    "bicarb soda",
    "bi-carb soda",
    "bicarb",
    "bi-carbonate soda",
    "baking soda",
    "bicarbonate soda",
    "sodium bicarbonate",
  ]),
  baking("cream of tartar"),
  baking("instant dried yeast", undefined, [
    "yeast",
    "dried yeast",
    "dry yeast",
    "instant yeast",
    "active dry yeast",
    "active dried yeast",
    "fast-action dried yeast",
    "fast-action yeast",
    "instant dry yeast",
    "rapid rise yeast",
  ]),
  baking("gelatine powder", undefined, [
    "powdered gelatine",
    "gelatine",
    "gelatin",
    "powdered gelatin",
    "unflavoured gelatine",
    "unflavored gelatin",
    "gelatin powder",
  ]),
  baking("gelatine sheets", undefined, [
    "gelatine titanium sheets",
    "titanium gelatine sheets",
    "gelatine leaves",
    "gelatin sheets",
    "leaf gelatine",
    "titanium-strength gelatine leaves",
  ]),
  baking("white sugar", undefined, [
    "golden granulated sugar",
    "sugar",
    "granulated sugar",
    "white granulated sugar",
    "regular sugar",
    "table sugar",
    "cane sugar",
    "granulated white sugar",
  ]),
  baking("caster sugar", undefined, ["superfine sugar", "castor sugar", "white caster sugar", "golden caster sugar"]),
  baking("brown sugar", undefined, [
    "light brown soft sugar",
    "soft light brown sugar",
    "light brown sugar",
    "soft brown sugar",
    "firmly packed brown sugar",
    "packed brown sugar",
    "light soft brown sugar",
  ]),
  baking("dark brown sugar", undefined, [
    "dark brown soft sugar",
    "soft dark brown sugar",
    "dark soft brown sugar",
    "muscovado sugar",
    "dark muscovado sugar",
    "light muscovado sugar",
  ]),
  baking("raw sugar", undefined, ["demerara sugar", "turbinado sugar", "raw caster sugar"]),
  baking("icing sugar", undefined, [
    "royal icing sugar",
    "gluten-free icing sugar",
    "powdered sugar",
    "confectioners sugar",
    "confectioners' sugar",
    "confectioner's sugar",
    "icing sugar mixture",
    "pure icing sugar",
    "soft icing sugar",
  ]),
  baking("palm sugar", undefined, ["grated palm sugar", "jaggery", "gula melaka"]),
  baking("coconut sugar"),
  baking("glucose syrup", undefined, ["karo syrup", "dark corn syrup", "liquid glucose", "glucose", "corn syrup", "light corn syrup"]),
  baking("vanilla extract", undefined, ["vanilla", "pure vanilla extract", "natural vanilla extract"]),
  baking("vanilla essence", undefined, ["imitation vanilla essence", "natural vanilla essence", "vanilla flavouring"]),
  baking("vanilla bean paste", undefined, ["vanilla paste"]),
  baking("vanilla bean", "vanilla beans", ["vanilla pod", "vanilla pods"]),
  baking("almond extract", undefined, ["almond essence"]),
  baking("rosewater", undefined, ["rose water"]),
  baking("orange blossom water", undefined, ["orange flower water"]),
  baking("cocoa powder", undefined, [
    "cocoa",
    "unsweetened cocoa powder",
    "dutch-processed cocoa",
    "dutch processed cocoa powder",
    "dutch cocoa",
    "dark cocoa powder",
  ]),
  baking("cacao powder", undefined, ["raw cacao powder", "cacao"]),
  baking("dark chocolate", undefined, [
    "good-quality dark chocolate",
    "quality dark chocolate",
    "dark eating chocolate",
    "bittersweet chocolate",
    "semi-sweet chocolate",
    "semisweet chocolate",
    "cooking chocolate",
    "dark cooking chocolate",
    "chocolate",
  ]),
  baking("milk chocolate", undefined, ["milk eating chocolate", "milk cooking chocolate"]),
  baking("white chocolate", undefined, ["good-quality white chocolate", "white eating chocolate", "white cooking chocolate"]),
  baking("chocolate chips", undefined, [
    "choc chips",
    "dark chocolate chips",
    "dark choc chips",
    "semi-sweet chocolate chips",
    "semisweet chocolate chips",
    "chocolate chip",
    "milk chocolate chips",
    "dark chocolate bits",
    "chocolate bits",
  ]),
  baking("white chocolate chips", undefined, ["white choc chips", "white chocolate bits"]),
  baking("chocolate melts", undefined, ["dark chocolate melts", "white chocolate melts", "milk chocolate melts", "candy melts"]),
  baking("sprinkles", undefined, ["hundreds and thousands", "rainbow sprinkles", "sprinkle", "nonpareils"]),
  baking("food colouring", undefined, [
    "food coloring",
    "gel food colouring",
    "red food colouring",
    "green food colouring",
    "food colour",
    "liquid food colouring",
  ]),
  baking("marshmallows", undefined, ["marshmallow", "mini marshmallows", "miniature marshmallows"]),
  baking("custard powder", undefined, ["instant custard powder"]),
  baking("milk powder", undefined, ["powdered milk", "skim milk powder", "dried milk powder"]),
  baking("plain sweet biscuits", undefined, [
    "plain biscuits",
    "sweet biscuits",
    "arrowroot biscuits",
    "marie biscuits",
    "digestive biscuits",
    "digestives",
    "graham crackers",
    "graham cracker crumbs",
  ]),
  baking("crystallised ginger", undefined, ["crystallized ginger", "glacé ginger", "glace ginger", "candied ginger", "stem ginger"]),
  baking("instant coffee", undefined, ["instant coffee powder", "instant coffee granules", "instant espresso powder", "espresso powder"]),

  // ── Spices
  spice("salt", undefined, [
    "coarse sea salt",
    "cooking salt",
    "table salt",
    "kosher salt",
    "fine salt",
    "fine sea salt",
    "sea salt",
    "coarse salt",
    "coarse cooking salt",
    "rock salt",
    "iodised salt",
    "pink salt",
    "himalayan salt",
    "river salt",
  ]),
  spice("sea salt flakes", undefined, ["salt flakes", "flaky sea salt", "flaked sea salt", "maldon salt", "sea salt flake", "flaky salt"]),
  {
    name: "salt and pepper",
    aliases: [
      "salt & pepper",
      "salt and black pepper",
      "salt and freshly ground black pepper",
      "sea salt and black pepper",
      "salt and ground black pepper",
      "salt and freshly cracked black pepper",
      "salt and cracked black pepper",
      "sea salt and freshly ground black pepper",
      "sea salt and cracked black pepper",
      "sea salt and freshly cracked black pepper",
      "salt and white pepper",
    ],
    aisle: "Spices",
    skipShopping: true,
  },
  spice("black pepper", undefined, [
    "pepper",
    "ground black pepper",
    "freshly ground black pepper",
    "cracked black pepper",
    "freshly cracked black pepper",
    "ground pepper",
    "freshly ground pepper",
    "cracked pepper",
    "coarsely ground black pepper",
  ]),
  spice("white pepper", undefined, ["ground white pepper", "white pepper powder"]),
  spice("black peppercorns", undefined, ["white peppercorns", "peppercorns", "whole black peppercorns", "black peppercorn", "whole peppercorns"]),
  spice("sichuan pepper", undefined, ["sichuan peppercorns", "szechuan peppercorns", "szechuan pepper", "sichuan peppercorn"]),
  spice("ground cumin", undefined, ["cumin", "cumin powder", "ground cumin powder"]),
  spice("cumin seeds", undefined, ["cumin seed", "whole cumin seeds", "whole cumin"]),
  spice("ground coriander", undefined, ["coriander powder", "ground coriander seeds"]),
  spice("coriander seeds", undefined, ["coriander seed", "whole coriander seeds"]),
  spice("paprika", undefined, ["sweet paprika", "paprika powder", "hungarian paprika", "ground paprika"]),
  spice("smoked paprika", undefined, ["sweet smoked paprika", "hot smoked paprika", "pimentón", "pimenton", "spanish smoked paprika", "smoked sweet paprika"]),
  spice("cayenne pepper", undefined, ["cayenne", "ground cayenne pepper", "cayenne powder"]),
  spice("chilli powder", undefined, ["chili powder", "red chilli powder", "ground chilli", "hot chilli powder", "mild chilli powder", "chile powder"]),
  spice("kashmiri chilli powder", undefined, ["kashmiri chili powder", "kashmiri chilli", "kashmiri red chilli powder"]),
  spice("chilli flakes", undefined, [
    "dried red chilli flakes",
    "dried chili flakes",
    "chili flakes",
    "dried chilli flakes",
    "red chilli flakes",
    "red pepper flakes",
    "crushed red pepper",
    "crushed red pepper flakes",
    "crushed chilli",
    "red chili flakes",
  ]),
  spice("dried chilli", "dried chillies", ["dried red chilli", "dried red chillies", "whole dried chillies", "dried chiles", "dried chili"]),
  spice("ground turmeric", undefined, ["turmeric", "turmeric powder", "tumeric", "ground tumeric", "tumeric powder"]),
  spice("ground cinnamon", undefined, ["cinnamon", "cinnamon powder", "ground cinnamon powder"]),
  spice("cinnamon stick", "cinnamon sticks", ["cinnamon quill", "cinnamon quills"]),
  spice("ground nutmeg", undefined, ["nutmeg", "freshly grated nutmeg", "whole nutmeg", "grated nutmeg"]),
  spice("ground ginger", undefined, ["ginger powder", "dried ginger"]),
  spice("ground cardamom", undefined, ["cardamom", "cardamom powder"]),
  spice("cardamom pods", undefined, ["cardamom pod", "green cardamom pods", "green cardamom", "whole cardamom pods"]),
  spice("ground cloves", undefined, ["clove powder"]),
  spice("whole cloves", undefined, ["whole clove"]),
  spice("ground allspice", undefined, ["all spice", "all spice powder", "allspice", "allspice powder"]),
  spice("mixed spice", undefined, ["pumpkin pie spice", "pumpkin spice", "ground mixed spice"]),
  spice("star anise", undefined, ["star anise pods", "whole star anise"]),
  spice("fennel seeds", undefined, ["fennel seed"]),
  spice("yellow mustard seeds", undefined, ["mustard seeds", "mustard seed", "yellow mustard seed"]),
  spice("black mustard seeds", undefined, ["brown mustard seeds", "black mustard seed", "brown mustard seed"]),
  spice("mustard powder", undefined, ["dry mustard", "english mustard powder", "ground mustard", "dry mustard powder"]),
  spice("fenugreek seeds", undefined, ["fenugreek seed", "fenugreek"]),
  spice("nigella seeds", undefined, ["nigella seed", "kalonji", "black onion seeds", "black cumin seeds"]),
  spice("caraway seeds", undefined, ["caraway seed", "caraway"]),
  spice("celery seeds", undefined, ["celery seed"]),
  spice("garam masala", undefined, ["garam marsala"]),
  spice("curry powder", undefined, ["mild curry powder", "hot curry powder", "madras curry powder"]),
  spice("chinese five spice", undefined, [
    "five spice",
    "five-spice",
    "five spice powder",
    "five-spice powder",
    "chinese five spice powder",
    "chinese five-spice",
  ]),
  spice("ras el hanout"),
  spice("za'atar", undefined, ["zaatar", "za’atar"]),
  spice("sumac", undefined, ["ground sumac"]),
  spice("dukkah", undefined, ["dukka"]),
  spice("cajun seasoning", undefined, ["cajun spice", "cajun spice mix", "creole seasoning"]),
  spice("taco seasoning", undefined, ["taco seasoning mix", "taco spice mix", "mexican seasoning", "fajita seasoning"]),
  spice("italian seasoning", undefined, ["italian herbs", "dried italian herbs", "italian herb mix", "italian herb seasoning"]),
  spice("dried mixed herbs", undefined, ["mixed herbs", "mixed dried herbs", "herbes de provence"]),
  spice("dried oregano", undefined, ["dried oregano leaves", "dry oregano"]),
  spice("dried thyme", undefined, ["dried thyme leaves", "dry thyme"]),
  spice("dried basil", undefined, ["dry basil"]),
  spice("dried rosemary", undefined, []),
  spice("dried parsley", undefined, ["parsley flakes", "dried parsley flakes"]),
  spice("dried dill", undefined, ["dill weed", "dried dill weed"]),
  spice("dried mint", undefined, ["dried mint leaves"]),
  spice("bay leaf", "bay leaves", ["dried bay leaf", "dried bay leaves", "fresh bay leaves", "fresh bay leaf"]),
  spice("saffron", undefined, ["saffron threads", "saffron strands", "pinch of saffron"]),
  spice("garlic powder", undefined, ["garlic granules", "granulated garlic", "dried garlic"]),
  spice("onion powder", undefined, ["onion granules", "granulated onion", "dried onion flakes", "onion flakes"]),
  spice("garlic salt"),
  spice("onion salt"),
  spice("aleppo pepper", undefined, ["pul biber", "aleppo chilli flakes", "turkish chilli flakes", "urfa biber"]),
  spice("celery salt"),
  spice("chicken salt"),
  spice("lemon pepper", undefined, ["lemon pepper seasoning"]),
  spice("seasoned salt", undefined, ["seasoning salt", "season salt"]),
  spice("poultry seasoning"),
  spice("msg", undefined, ["monosodium glutamate", "accent seasoning"]),
  spice("juniper berries", undefined, ["juniper berry"]),
  spice("ground mace", undefined, ["mace", "mace blade", "mace blades"]),
  spice("cassia bark", undefined, ["cassia"]),
  spice("chaat masala"),
  spice("baharat", undefined, ["baharat spice mix", "arabic mixed spice", "lebanese seven spice", "seven spice"]),
  spice("shichimi togarashi", undefined, ["shichimi", "togarashi", "japanese seven spice"]),
  spice("barberries", undefined, ["dried barberries", "zereshk"]),
  spice("vanilla sugar"),
  spice("cinnamon sugar"),
  spice("nutritional yeast", undefined, ["nutritional yeast flakes", "savoury yeast flakes"]),

  // ── International
  international("soy sauce", undefined, [
    "light soy sauce",
    "all-purpose soy sauce",
    "soya sauce",
    "low-salt soy sauce",
    "salt-reduced soy sauce",
    "reduced-salt soy sauce",
    "low-sodium soy sauce",
    "reduced salt soy sauce",
    "japanese soy sauce",
    "light soy",
    "soy",
  ]),
  international("dark soy sauce", undefined, ["dark soy", "thick soy sauce"]),
  international("kecap manis", undefined, ["sweet soy sauce", "ketjap manis"]),
  international("tamari", undefined, ["gluten-free tamari", "tamari sauce"]),
  international("fish sauce", undefined, ["thai fish sauce", "nam pla"]),
  international("oyster sauce", undefined, ["vegetarian oyster sauce"]),
  international("hoisin sauce", undefined, ["hoi sin sauce", "hoisin"]),
  international("chinese cooking wine", undefined, [
    "rice wine",
    "shao hsing wine",
    "chinese wine",
    "shaoxing wine",
    "shaoxing",
    "shao xing wine",
    "chinese rice wine",
    "shaoxing cooking wine",
  ]),
  international("mirin", undefined, ["mirin seasoning", "sweet rice wine"]),
  international("sake", undefined, ["cooking sake"]),
  international("rice vinegar", undefined, ["rice wine vinegar", "japanese rice vinegar", "seasoned rice vinegar"]),
  international("chinese black vinegar", undefined, ["chinkiang vinegar", "black vinegar", "chinese black rice vinegar"]),
  international("sesame paste", undefined, ["chinese sesame paste"]),
  international("chilli oil", undefined, ["chili oil", "chilli crisp", "chili crisp", "chiu chow chilli oil", "crispy chilli oil"]),
  international("chilli bean paste", undefined, ["doubanjiang", "toban djan", "spicy bean paste"]),
  international("gochujang", undefined, ["korean chilli paste", "korean red pepper paste"]),
  international("gochugaru", undefined, ["korean chilli flakes", "korean red pepper flakes"]),
  international("sambal oelek", undefined, ["sambal olek", "sambal ulek", "sambal", "chilli paste", "chili paste"]),
  international("chilli jam", undefined, ["chili jam", "thai chilli jam", "nam prik pao"]),
  international("wasabi", undefined, ["wasabi paste", "wasabi powder"]),
  international("matcha powder", undefined, ["matcha", "green tea powder", "matcha green tea powder"]),
  international("red bean paste", undefined, ["sweet red bean paste", "adzuki bean paste", "anko"]),
  international("dried mexican chillies", undefined, [
    "guajillo chillies",
    "guajillo chiles",
    "ancho chillies",
    "ancho chiles",
    "ancho chilli",
    "pasilla chillies",
    "dried ancho chillies",
    "dried guajillo chillies",
  ]),
  international("enchilada sauce", undefined, ["red enchilada sauce", "green enchilada sauce"]),
  international("miso paste", undefined, ["miso", "white miso", "white miso paste", "shiro miso", "red miso", "red miso paste"]),
  international("char siu sauce", undefined, ["chinese barbecue sauce"]),
  international("plum sauce"),
  international("teriyaki sauce", undefined, ["teriyaki marinade"]),
  international("satay sauce", undefined, ["peanut sauce"]),
  international("shrimp paste", undefined, ["belacan", "blachan"]),
  international("tamarind paste", undefined, ["tamarind puree", "tamarind purée", "tamarind concentrate", "tamarind"]),
  international("thai red curry paste", undefined, ["red curry paste", "red thai curry paste"]),
  international("thai green curry paste", undefined, ["green curry paste", "green thai curry paste"]),
  international("massaman curry paste", undefined, ["massaman paste"]),
  international("yellow curry paste", undefined, ["thai yellow curry paste"]),
  international("curry paste", undefined, [
    "tikka masala curry paste",
    "jalfrezi curry paste",
    "indian curry paste",
    "korma paste",
    "tikka masala paste",
    "tandoori paste",
    "rogan josh paste",
    "madras curry paste",
  ]),
  international("harissa", undefined, ["harissa paste", "rose harissa"]),
  international("chipotle in adobo", undefined, [
    "chipotle chillies in adobo",
    "chipotle peppers in adobo",
    "chipotle chiles in adobo",
    "chipotle in adobo sauce",
    "chipotle chilli in adobo sauce",
    "chipotle chillies",
    "chipotle",
  ]),
  international("refried beans", undefined, ["canned refried beans"]),
  international("coconut water"),
  international("rice paper", undefined, ["rice paper wrappers", "rice paper sheets", "rice paper rounds", "rice paper rolls"]),
  international("nori", undefined, ["nori sheets", "nori sheet", "seaweed sheets", "sushi nori"]),
  international("dashi", undefined, ["dashi powder", "dashi stock", "instant dashi"]),
  international("bonito flakes", undefined, ["katsuobushi"]),
  international("dried shrimp", undefined, ["dried prawns", "dried shrimps"]),
  international("urad dal", undefined, ["urad dhal", "black gram", "split urad dal"]),
  international("poppadoms", undefined, ["poppadom", "pappadums", "papadums", "uncooked poppadoms"]),
  international("crispy fried shallots", undefined, ["fried shallots", "fried asian shallots", "crispy shallots", "fried onions", "crispy fried onions"]),
  international("pickled ginger", undefined, ["sushi ginger", "gari"]),
  international("kimchi", undefined, ["cabbage kimchi"]),
  international("wonton wrappers", undefined, [
    "wonton wrapper",
    "wonton skins",
    "gow gee wrappers",
    "dumpling wrappers",
    "gyoza wrappers",
    "dumpling wrapper",
  ]),
  international("spring roll wrappers", undefined, ["spring roll pastry", "spring roll wrapper", "spring roll sheets"]),
  international("coconut yoghurt", undefined, ["coconut yogurt"]),

  // ── Drinks
  drinks("white wine", undefined, ["dry white wine", "chardonnay", "sauvignon blanc", "pinot grigio", "white cooking wine"]),
  drinks("red wine", undefined, ["dry red wine", "shiraz", "cabernet sauvignon", "merlot", "pinot noir", "red cooking wine"]),
  drinks("dry sherry", undefined, ["sherry", "cooking sherry", "fino sherry"]),
  drinks("marsala", undefined, ["marsala wine", "dry marsala"]),
  drinks("vermouth", undefined, ["dry vermouth", "sweet vermouth", "white vermouth"]),
  drinks("port", undefined, ["tawny port"]),
  drinks("sparkling wine", undefined, ["prosecco", "champagne", "cava"]),
  drinks("beer", undefined, ["lager", "pale ale", "stout", "guinness", "dark beer"]),
  drinks("cider", undefined, ["apple cider", "dry cider", "hard cider"]),
  drinks("brandy", undefined, ["cognac"]),
  drinks("rum", undefined, ["dark rum", "white rum", "spiced rum", "golden rum"]),
  drinks("vodka"),
  drinks("gin"),
  drinks("whisky", undefined, ["whiskey", "bourbon", "scotch whisky"]),
  drinks("tequila"),
  drinks("orange liqueur", undefined, ["cointreau", "grand marnier", "triple sec"]),
  drinks("coffee liqueur", undefined, ["kahlua", "kahlúa", "tia maria"]),
  drinks("orange juice", undefined, ["juice of orange", "juice of an orange", "freshly squeezed orange juice", "fresh orange juice"]),
  drinks("apple juice", undefined, ["cloudy apple juice", "unsweetened apple juice"]),
  drinks("pineapple juice"),
  drinks("cranberry juice"),
  drinks("soda water", undefined, ["sparkling water", "club soda", "sparkling mineral water", "mineral water"]),
  drinks("tonic water", undefined, ["tonic"]),
  drinks("lemonade"),
  drinks("ginger beer", undefined, ["ginger ale"]),
  drinks("coffee", undefined, ["espresso", "brewed coffee", "strong coffee", "freshly brewed coffee", "espresso coffee", "strong black coffee", "hot coffee"]),
  drinks("tea bags", undefined, ["tea bag", "black tea bags", "black tea", "green tea", "green tea bags"]),
  drinks("almond milk", undefined, ["unsweetened almond milk"]),
  drinks("soy milk", undefined, ["soya milk", "unsweetened soy milk"]),
  drinks("oat milk", undefined, ["unsweetened oat milk"]),
  drinks("elderflower cordial"),
  drinks("limoncello"),
  drinks("angostura bitters", undefined, ["bitters"]),
  drinks("kefir", undefined, ["milk kefir", "kefir yoghurt"]),

  // ── Freezer
  freezer("peas", undefined, ["frozen peas", "green peas", "garden peas", "baby peas", "podded peas", "fresh peas", "pea", "petite peas"]),
  freezer("frozen spinach", undefined, ["frozen chopped spinach"]),
  freezer("frozen berries", undefined, ["frozen mixed berries", "mixed berries", "berries", "mixed frozen berries", "fresh berries"]),
  freezer("frozen raspberries", undefined, ["frozen raspberry"]),
  freezer("frozen blueberries", undefined, ["frozen blueberry"]),
  freezer("frozen mango", undefined, ["frozen mango chunks"]),
  freezer("edamame", undefined, ["frozen edamame", "shelled edamame", "edamame beans", "soy beans", "soybeans"]),
  freezer("broad beans", undefined, ["frozen broad beans", "fava beans", "broad bean", "fava bean"]),
  freezer("hash browns", undefined, ["hash brown", "hash brown potatoes", "frozen hash browns"]),
  freezer("mixed vegetables", undefined, ["frozen mixed vegetables", "frozen vegetables", "frozen mixed veg", "mixed veg"]),
  freezer("puff pastry", undefined, [
    "puff pastry sheets",
    "puff pastry sheet",
    "ready-rolled puff pastry",
    "ready rolled puff pastry",
    "butter puff pastry",
    "frozen puff pastry",
    "ready-rolled butter puff pastry",
    "all-butter puff pastry",
  ]),
  freezer("shortcrust pastry", undefined, [
    "pie shells",
    "unbaked pie shell",
    "pastry shell",
    "shortcrust pastry sheets",
    "shortcrust pastry sheet",
    "ready-rolled shortcrust pastry",
    "sweet shortcrust pastry",
    "pie crust",
    "pastry case",
    "pie shell",
  ]),
  freezer("filo pastry", undefined, ["filo", "phyllo pastry", "phyllo", "filo sheets", "phyllo dough", "fillo pastry"]),
  freezer("vanilla ice cream", undefined, ["ice cream", "vanilla ice-cream", "ice-cream", "vanilla bean ice cream"]),
  freezer("ice", undefined, ["ice cubes", "ice cube", "crushed ice"]),

  // ── Water: from the tap, never on a list
  {
    name: "water",
    aliases: [
      "cold water",
      "hot water",
      "warm water",
      "boiling water",
      "lukewarm water",
      "tap water",
      "iced water",
      "ice water",
      "tepid water",
      "filtered water",
      "chilled water",
      "room temperature water",
      "just-boiled water",
    ],
    aisle: "Pantry",
    skipShopping: true,
  },
];
