/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiImagesFileRouteImport } from './routes/api/images/$file'
import { Route as ApiRecipesIdImageRouteImport } from './routes/api/recipes/$id/image'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesFileRoute = ApiImagesFileRouteImport.update({
  id: '/api/images/$file',
  path: '/api/images/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecipesIdImageRoute = ApiRecipesIdImageRouteImport.update({
  id: '/api/recipes/$id/image',
  path: '/api/recipes/$id/image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/images/$file': typeof ApiImagesFileRoute
  '/api/recipes/$id/image': typeof ApiRecipesIdImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/images/$file': typeof ApiImagesFileRoute
  '/api/recipes/$id/image': typeof ApiRecipesIdImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/images/$file': typeof ApiImagesFileRoute
  '/api/recipes/$id/image': typeof ApiRecipesIdImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api/health' | '/api/images/$file' | '/api/recipes/$id/image'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/health' | '/api/images/$file' | '/api/recipes/$id/image'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/api/images/$file'
    | '/api/recipes/$id/image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiImagesFileRoute: typeof ApiImagesFileRoute
  ApiRecipesIdImageRoute: typeof ApiRecipesIdImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/$file': {
      id: '/api/images/$file'
      path: '/api/images/$file'
      fullPath: '/api/images/$file'
      preLoaderRoute: typeof ApiImagesFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recipes/$id/image': {
      id: '/api/recipes/$id/image'
      path: '/api/recipes/$id/image'
      fullPath: '/api/recipes/$id/image'
      preLoaderRoute: typeof ApiRecipesIdImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiImagesFileRoute: ApiImagesFileRoute,
  ApiRecipesIdImageRoute: ApiRecipesIdImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
