/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as RecipesNewRouteImport } from './routes/recipes/new'
import { Route as ApiImagesFileRouteImport } from './routes/api/images/$file'
import { Route as RecipesSlugIndexRouteImport } from './routes/recipes/$slug/index'
import { Route as RecipesSlugCookRouteImport } from './routes/recipes/$slug/cook'
import { Route as RecipesSlugEditRouteImport } from './routes/recipes/$slug/edit'
import { Route as ApiImagesTimelineFileRouteImport } from './routes/api/images/timeline/$file'
import { Route as ApiRecipesIdImageRouteImport } from './routes/api/recipes/$id/image'
import { Route as ApiTimelineIdImageRouteImport } from './routes/api/timeline/$id/image'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesNewRoute = RecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesFileRoute = ApiImagesFileRouteImport.update({
  id: '/api/images/$file',
  path: '/api/images/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesSlugIndexRoute = RecipesSlugIndexRouteImport.update({
  id: '/recipes/$slug/',
  path: '/recipes/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesSlugCookRoute = RecipesSlugCookRouteImport.update({
  id: '/recipes/$slug/cook',
  path: '/recipes/$slug/cook',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesSlugEditRoute = RecipesSlugEditRouteImport.update({
  id: '/recipes/$slug/edit',
  path: '/recipes/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesTimelineFileRoute = ApiImagesTimelineFileRouteImport.update({
  id: '/api/images/timeline/$file',
  path: '/api/images/timeline/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecipesIdImageRoute = ApiRecipesIdImageRouteImport.update({
  id: '/api/recipes/$id/image',
  path: '/api/recipes/$id/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTimelineIdImageRoute = ApiTimelineIdImageRouteImport.update({
  id: '/api/timeline/$id/image',
  path: '/api/timeline/$id/image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
  '/api/health': typeof ApiHealthRoute
  '/recipes/new': typeof RecipesNewRoute
  '/api/images/$file': typeof ApiImagesFileRoute
  '/recipes/$slug/cook': typeof RecipesSlugCookRoute
  '/recipes/$slug/edit': typeof RecipesSlugEditRoute
  '/recipes/$slug/': typeof RecipesSlugIndexRoute
  '/api/images/timeline/$file': typeof ApiImagesTimelineFileRoute
  '/api/recipes/$id/image': typeof ApiRecipesIdImageRoute
  '/api/timeline/$id/image': typeof ApiTimelineIdImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
  '/api/health': typeof ApiHealthRoute
  '/recipes/new': typeof RecipesNewRoute
  '/api/images/$file': typeof ApiImagesFileRoute
  '/recipes/$slug/cook': typeof RecipesSlugCookRoute
  '/recipes/$slug/edit': typeof RecipesSlugEditRoute
  '/recipes/$slug': typeof RecipesSlugIndexRoute
  '/api/images/timeline/$file': typeof ApiImagesTimelineFileRoute
  '/api/recipes/$id/image': typeof ApiRecipesIdImageRoute
  '/api/timeline/$id/image': typeof ApiTimelineIdImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
  '/api/health': typeof ApiHealthRoute
  '/recipes/new': typeof RecipesNewRoute
  '/api/images/$file': typeof ApiImagesFileRoute
  '/recipes/$slug/cook': typeof RecipesSlugCookRoute
  '/recipes/$slug/edit': typeof RecipesSlugEditRoute
  '/recipes/$slug/': typeof RecipesSlugIndexRoute
  '/api/images/timeline/$file': typeof ApiImagesTimelineFileRoute
  '/api/recipes/$id/image': typeof ApiRecipesIdImageRoute
  '/api/timeline/$id/image': typeof ApiTimelineIdImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/shopping'
    | '/api/health'
    | '/recipes/new'
    | '/api/images/$file'
    | '/recipes/$slug/cook'
    | '/recipes/$slug/edit'
    | '/recipes/$slug/'
    | '/api/images/timeline/$file'
    | '/api/recipes/$id/image'
    | '/api/timeline/$id/image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/shopping'
    | '/api/health'
    | '/recipes/new'
    | '/api/images/$file'
    | '/recipes/$slug/cook'
    | '/recipes/$slug/edit'
    | '/recipes/$slug'
    | '/api/images/timeline/$file'
    | '/api/recipes/$id/image'
    | '/api/timeline/$id/image'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/shopping'
    | '/api/health'
    | '/recipes/new'
    | '/api/images/$file'
    | '/recipes/$slug/cook'
    | '/recipes/$slug/edit'
    | '/recipes/$slug/'
    | '/api/images/timeline/$file'
    | '/api/recipes/$id/image'
    | '/api/timeline/$id/image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  ShoppingRoute: typeof ShoppingRoute
  ApiHealthRoute: typeof ApiHealthRoute
  RecipesNewRoute: typeof RecipesNewRoute
  ApiImagesFileRoute: typeof ApiImagesFileRoute
  RecipesSlugCookRoute: typeof RecipesSlugCookRoute
  RecipesSlugEditRoute: typeof RecipesSlugEditRoute
  RecipesSlugIndexRoute: typeof RecipesSlugIndexRoute
  ApiImagesTimelineFileRoute: typeof ApiImagesTimelineFileRoute
  ApiRecipesIdImageRoute: typeof ApiRecipesIdImageRoute
  ApiTimelineIdImageRoute: typeof ApiTimelineIdImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/new': {
      id: '/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof RecipesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/$file': {
      id: '/api/images/$file'
      path: '/api/images/$file'
      fullPath: '/api/images/$file'
      preLoaderRoute: typeof ApiImagesFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$slug/': {
      id: '/recipes/$slug/'
      path: '/recipes/$slug'
      fullPath: '/recipes/$slug/'
      preLoaderRoute: typeof RecipesSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$slug/cook': {
      id: '/recipes/$slug/cook'
      path: '/recipes/$slug/cook'
      fullPath: '/recipes/$slug/cook'
      preLoaderRoute: typeof RecipesSlugCookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$slug/edit': {
      id: '/recipes/$slug/edit'
      path: '/recipes/$slug/edit'
      fullPath: '/recipes/$slug/edit'
      preLoaderRoute: typeof RecipesSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/timeline/$file': {
      id: '/api/images/timeline/$file'
      path: '/api/images/timeline/$file'
      fullPath: '/api/images/timeline/$file'
      preLoaderRoute: typeof ApiImagesTimelineFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recipes/$id/image': {
      id: '/api/recipes/$id/image'
      path: '/api/recipes/$id/image'
      fullPath: '/api/recipes/$id/image'
      preLoaderRoute: typeof ApiRecipesIdImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/timeline/$id/image': {
      id: '/api/timeline/$id/image'
      path: '/api/timeline/$id/image'
      fullPath: '/api/timeline/$id/image'
      preLoaderRoute: typeof ApiTimelineIdImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ShoppingRoute: ShoppingRoute,
  ApiHealthRoute: ApiHealthRoute,
  RecipesNewRoute: RecipesNewRoute,
  ApiImagesFileRoute: ApiImagesFileRoute,
  RecipesSlugCookRoute: RecipesSlugCookRoute,
  RecipesSlugEditRoute: RecipesSlugEditRoute,
  RecipesSlugIndexRoute: RecipesSlugIndexRoute,
  ApiImagesTimelineFileRoute: ApiImagesTimelineFileRoute,
  ApiRecipesIdImageRoute: ApiRecipesIdImageRoute,
  ApiTimelineIdImageRoute: ApiTimelineIdImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
